ALTER TYPE "esign_document_type" ADD VALUE IF NOT EXISTS 'EARLY_TERMINATION_AGREEMENT';
ALTER TYPE "esign_document_type" ADD VALUE IF NOT EXISTS 'RECOVERY_AUTHORITY';

ALTER TYPE "esign_signing_stage" ADD VALUE IF NOT EXISTS 'STAGE4_EARLY_TERMINATION';
ALTER TYPE "esign_signing_stage" ADD VALUE IF NOT EXISTS 'STAGE5_RECOVERY_AUTHORITY';
