ALTER TYPE "vehicle_model" ADD VALUE IF NOT EXISTS 'ET5T';
ALTER TYPE "vehicle_model" ADD VALUE IF NOT EXISTS 'EC6';
ALTER TYPE "vehicle_model" ADD VALUE IF NOT EXISTS 'ES8';
ALTER TYPE "vehicle_model" ADD VALUE IF NOT EXISTS 'ET9';
ALTER TYPE "vehicle_model" ADD VALUE IF NOT EXISTS 'ES9';
